insert into communes (name, type, district_old, description, slug)
values
  ('Hưng Điền', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hung-dien'),
  ('Vĩnh Thạnh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'vinh-thanh'),
  ('Tân Hưng', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-hung'),
  ('Vĩnh Châu', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'vinh-chau'),
  ('Tuyên Bình', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tuyen-binh'),
  ('Vĩnh Hưng', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'vinh-hung'),
  ('Khánh Hưng', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'khanh-hung'),
  ('Tuyên Thạnh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tuyen-thanh'),
  ('Bình Hiệp', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'binh-hiep'),
  ('Bình Hòa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'binh-hoa'),
  ('Mộc Hóa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'moc-hoa'),
  ('Hậu Thạnh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hau-thanh'),
  ('Nhơn Hòa Lập', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'nhon-hoa-lap'),
  ('Nhơn Ninh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'nhon-ninh'),
  ('Tân Thạnh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-thanh'),
  ('Bình Thành', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'binh-thanh'),
  ('Thạnh Phước', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thanh-phuoc'),
  ('Thạnh Hóa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thanh-hoa'),
  ('Tân Tây', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-tay'),
  ('Thủ Thừa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thu-thua'),
  ('Mỹ An', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'my-an'),
  ('Mỹ Thạnh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'my-thanh'),
  ('Tân Long', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-long'),
  ('Mỹ Quý', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'my-quy'),
  ('Đông Thành', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'dong-thanh'),
  ('Đức Huệ', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'duc-hue'),
  ('An Ninh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'an-ninh'),
  ('Hiệp Hòa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hiep-hoa'),
  ('Hậu Nghĩa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hau-nghia'),
  ('Hòa Khánh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hoa-khanh'),
  ('Đức Lập', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'duc-lap'),
  ('Mỹ Hạnh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'my-hanh'),
  ('Đức Hòa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'duc-hoa'),
  ('Thạnh Lợi', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thanh-loi'),
  ('Bình Đức', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'binh-duc'),
  ('Lương Hòa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'luong-hoa'),
  ('Bến Lức', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'ben-luc'),
  ('Mỹ Yên', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'my-yen'),
  ('Long Cang', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'long-cang'),
  ('Rạch Kiến', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'rach-kien'),
  ('Mỹ Lệ', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'my-le'),
  ('Tân Lân', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-lan'),
  ('Cần Đước', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'can-duoc'),
  ('Long Hựu', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'long-huu'),
  ('Phước Lý', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'phuoc-ly'),
  ('Mỹ Lộc', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'my-loc'),
  ('Cần Giuộc', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'can-giuoc'),
  ('Phước Vĩnh Tây', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'phuoc-vinh-tay'),
  ('Tân Tập', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-tap'),
  ('Vàm Cỏ', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'vam-co'),
  ('Tân Trụ', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-tru'),
  ('Nhựt Tảo', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'nhut-tao'),
  ('Thuận Mỹ', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thuan-my'),
  ('An Lục Long', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'an-luc-long'),
  ('Tầm Vu', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tam-vu'),
  ('Vĩnh Công', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'vinh-cong'),
  ('Phước Chỉ', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'phuoc-chi'),
  ('Hưng Thuận', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hung-thuan'),
  ('Thạnh Đức', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thanh-duc'),
  ('Phước Thạnh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'phuoc-thanh'),
  ('Truông Mít', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'truong-mit'),
  ('Lộc Ninh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'loc-ninh'),
  ('Cầu Khởi', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'cau-khoi'),
  ('Dương Minh Châu', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'duong-minh-chau'),
  ('Tân Đông', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-dong'),
  ('Tân Châu', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-chau'),
  ('Tân Phú', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-phu'),
  ('Tân Hội', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-hoi'),
  ('Tân Thành', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-thanh-2'),
  ('Tân Hòa', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-hoa'),
  ('Tân Lập', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-lap'),
  ('Tân Biên', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-bien'),
  ('Thạnh Bình', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thanh-binh'),
  ('Trà Vong', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tra-vong'),
  ('Phước Vinh', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'phuoc-vinh'),
  ('Hòa Hội', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hoa-hoi'),
  ('Ninh Điền', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'ninh-dien'),
  ('Châu Thành', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'chau-thanh'),
  ('Hảo Đước', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hao-duoc'),
  ('Long Chữ', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'long-chu'),
  ('Long Thuận', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'long-thuan'),
  ('Bến Cầu', 'xa', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'ben-cau'),
  ('Kiến Tường', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'kien-tuong'),
  ('Long An', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'long-an'),
  ('Tân An', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-an'),
  ('Khánh Hậu', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'khanh-hau'),
  ('Tân Ninh', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'tan-ninh'),
  ('Bình Minh', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'binh-minh'),
  ('Ninh Thạnh', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'ninh-thanh'),
  ('Long Hoa', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'long-hoa'),
  ('Hòa Thành', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'hoa-thanh'),
  ('Thanh Điền', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'thanh-dien'),
  ('Trảng Bàng', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'trang-bang'),
  ('An Tịnh', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'an-tinh'),
  ('Gò Dầu', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'go-dau'),
  ('Gia Lộc', 'phuong', 'Đơn vị hành chính sau sắp xếp năm 2025', 'Hồ sơ địa chí đang được số hóa theo từng đợt. Giai đoạn đầu ưu tiên bản đọc thử, thông tin nguồn và hướng dẫn liên hệ thư viện.', 'gia-loc')
on conflict (slug) do update
set
  name = excluded.name,
  type = excluded.type,
  district_old = excluded.district_old,
  description = excluded.description;
